# Generated by Django 5.2.4 on 2025-07-29 00:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('currency', models.CharField(default='USD', max_length=32)),
                ('email', models.EmailField(default='', max_length=256)),
                ('language', models.CharField(default='EN-US', max_length=32)),
                ('name', models.CharField(default='', max_length=256)),
                ('phone_number', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('geojson_information',
                 django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 related_name='service_areas', to='core.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
