'''
Django has some problems with postgis.
This migration fix that.
'''
# Generated by Django 5.2.4 on 2025-07-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            ALTER TABLE core_servicearea 
            DROP COLUMN IF EXISTS geojson_information;

            ALTER TABLE core_servicearea 
            ADD COLUMN geojson_information geometry(POLYGON, 4326);
            ''',
            reverse_sql='''
            ALTER TABLE core_servicearea 
            DROP COLUMN IF EXISTS geojson_information;

            ALTER TABLE core_servicearea 
            ADD COLUMN geojson_information jsonb;
            '''
        )
    ]
