'''
A index for improve GET by lat/lng operations
'''
# Generated by Django 5.2.4 on 2025-07-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250729_0056'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX idx_geojson_information_gist ON core_servicearea USING GIST (geojson_information)'
        )
    ]
